### ISSUE TITLE
Add support for documenting class properties and methods

### ISSUE THREAD

**Issue by TheSonOfThomp** [South-Paw/storybook-addon-overview-angular#11]
Sometimes you may want to document class attributes for a component, directive, module or service (particularly for services associated with storybook components i.e. `MyIconRegistry`)

Adding support for something like this may be useful.
> ## Properties
> `className`:  `get` `string`
> 
> The class name applied to the DOM element

**Comment by TheSonOfThomp** [comment]
Initial PR #12

**Comment by South-Paw** [comment]
Duplicate of #6

**Comment by South-Paw** [comment]
Wait. I don't know why I thought this was a duplicate... sorry.
