### ISSUE TITLE
Array parameters of generic type are not supported for set input

### ISSUE THREAD

**Issue by undsoft** [South-Paw/storybook-addon-overview-angular#21]
This:
```
@Input() set selectedItems(selectedItems: T[])
```

breaks the documentation in properties.component.ts line 18, because param.type is equal to:
```
{
  elementType: {
     type: "typeParameter",
     name: "T",
  },
  name: "T"
}
```

when the code reaches for non-existent `name` key.

**Comment by South-Paw** [comment]
Why would you want to use an any type array though? 🤔

Couldn't you also just use `Array<Any>` as the type?

**Comment by undsoft** [comment]
It's not an any type array, it's an array of T.
Example would be dropdown component rendering objects of various kind.

**Comment by South-Paw** [comment]
I'm not super familiar with Typescript types but does `Array<T>` work then?

I also don't understand why you'd want to document a generic in this tool, wouldn't you want to have a union of types or something so it more useful to the person implementing it?

Nevertheless, doesn't feel like it should error on a generic type.

**Comment by undsoft** [comment]
Array<T> and T[] are the same thing. Array<T> doesn't work either.

Generics can be useful when you want to work with many types, but also don't want to lose type safety. I.e. generic autocompletes, drop downs or tag inputs that allow various objects as input. 
Here's a made up example.
```typescript
@Component({
  selector: 'simple-example',
  template: '{{ processedItem[showKey] }}',
})
export class AutocompleteComponent<T> {
  @Input() showKey: keyof T;
  @Input() set item(item: T[]) {
    this.processedItem = item;
  }

  processedItem: T[];
}
```

Interestingly enough if setters are not used, but a property with T[] is defined:
```
@Input() item: T[] = [];
```
then, while they type is not shown correctly in the overview, it at least doesn't error.

It would still be good to see the type though.

**Comment by rheimus** [comment]
Do you have a more concrete example of what value this provides? While the typdoc bug is valid and should be fixed I am struggling to see a reason for making a generic component, it provides no particular value in the component itself and is ignored in templates when using the component, it also does not appear to provide any debugging value.

Are you using this for type checking when custom rendering components?

General repro of a generic component:
https://stackblitz.com/edit/angular-6jnfas?file=src%2Fapp%2Fgenerics%2Fgenerics.component.ts

**Comment by undsoft** [comment]
Are we discussing generic component vs any or generic component vs component working with unions?
Because sure, specifying a component with a more narrow type is better. But it's not always possible.

In our project, we have a generic Autocomplete component. It renders a string from one of the fields of the items (keyof T) and emits the whole T object, when user selects an item. This component can work with basically any type of object and is used throughout the system.

With regards to debugging value:
* You get type checking when creating components with ComponentFactoryResolver, like you did.
* You get suggestions and type checking in tests.
* While typescript doesn't prevent developer from making mistakes in angular templates, Webstorm will show a warning for <app-generics [key]="'incorrect-key'" [items]="items">

**Comment by rheimus** [comment]
Interesting, thanks for the detailed reply. 
Sounds like webstorm has gotten quite a bit better than the last time I tried it out. Template type hints are definitely worthwhile, have been using vscode so far and the Angular plugin for it does not give you any type safety in templates for component inputs.

**Comment by South-Paw** [comment]
@undsoft I've fixed the error breaking the addon for you with e0c59a7.

I haven't looked into correcting the appearance of the type, only ensuring that it is shown and doesn't break the addon.

If you (or your company) could find some time to look into it further that then I'm sure others would appreciate it as well 🙂
