### ISSUE TITLE
Version 1.0.0 is not importable from config.js

### ISSUE THREAD

**Issue by undsoft** [South-Paw/storybook-addon-overview-angular#22]
Hey,

Looks like new version (1.0.0) doesn't have index.js, but instead has index.ts.

Is this a mistake or does that mean that I need to change something in my setup to make it work?

Currently I just get "Module not found" errors.

**Comment by South-Paw** [comment]
A bugger... 🤦‍♂ 

That one is certainly my mistake, I'll create a fix asap.

**Comment by South-Paw** [comment]
@undsoft I've pushed 1.0.1 to the registry, could you install it and confirm it's working again 😅

**Comment by undsoft** [comment]
Thanks, appears to be working.
